spring:
  application:
    name: bot
  h2:
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      continue-on-error: true

  #todo encoding on web server
  datasource:
    url: jdbc:postgresql://localhost:5432/password-manager
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 7889
  error:
    include-message: always

telegram:
  bot:
    token: ENC(lk8BzUecUXkOKwYSfOUdZ9Z3gLgBqWknMf9BoUzme5zY3ipB9c9jq42wQQf35T/Wc8q3EO/kcy0qMPH1hlB9vRJCbBV9MsElcIKfE3kG66Y=)
    username: dev_password_manager_bot

app:
  base:
    url: http://localhost:7881